# List of available make goals:
#
# all                     Default target, builds the project
# clean                   Clean up the project
# rebuild                 Rebuild the project
#
#
# doc                     Build the documentation
# cleandoc                Clean up the documentation
# rebuilddoc              Rebuild the documentation
#
MAKEFILE_PATH = ../xdk/sam0/utils/make/Makefile.sam.in
include $(MAKEFILE_PATH)
